apiVersion: v1
kind: Service
metadata:
  name: appforservice 
  labels:
    app: appforservice 
spec:
  type: NodePort
  selector:
    app: appfroservice 
  ports:
  - protocol: TCP
    port: 8081
    name: http
  selector:
    app: appforstream
